server:
  port: 8090

spring:
  application:
    name: minimercado-gateway
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: http://localhost:8080
          predicates:
            - Path=/api/productos/**  # Ruta que el gateway redirigirá
          filters:
            - RewritePath=/api/productos/(?<segment>.*), /productos/${segment}