services:
  mongodb:
    container_name: minimercado-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: puntos
    ports:
      - "27017:27017"
    volumes:
      - minimercado:/data/mongodb
    networks:
      - minimercado

  api:
    container_name: minimercado-servicio-productos
    build:
      context: ../minimercado-servicio-productos
    restart: always
    environment:
      SPRING_DATA_MONGODB_HOST: "mongodb"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "productos"
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: "admin"
      SPRING_DATA_MONGODB_USERNAME: "root"
      SPRING_DATA_MONGODB_PASSWORD: "puntos"
      SPRING_APPLICATION_NAME: "minimercado-servicio-productos"
    ports:
      - "8080:8080"
    networks:
      - minimercado
    depends_on:
      - mongodb

  # api-gateway:
  #   container_name: api-gateway
  #   build:
  #     context: ../gateway
  #   restart: always
  #   ports:
  #     - "8090:8090"
  #   networks:
  #     - minimercado

  web:
    container_name: minimercado-web
    build:
      context: ../web/minimercado-front
      args:
        REACT_APP_API_URL: $REACT_APP_API_URL
    restart: always
    ports:
      - 3000:3000
    networks:
      - minimercado

volumes:
  minimercado:

networks:
  minimercado:
    driver: bridge